package com.sandwich.app.models.model.enums;

public enum OrderStatus {
    PENDING,
    PAYMENT_PROCESSING,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    RESTAURANT_ACCEPTED,
    RESTAURANT_REJECTED,
    RESTAURANT_FAILED,
    DELIVERY_ASSIGNED,
    DELIVERY_COMPLETED,
    DELIVERY_FAILED,
    COMPLETED,
    CANCELLED
}
